In [1]:
import numpy as np

In [2]:
# Exercise 1 Basic Indexing
numbers = np.array([10, 20, 30, 40, 50, 60])
print(numbers[2])
print(numbers[5])
print(numbers[1:])
print(numbers[::2])

30
60
[20 30 40 50 60]
[10 30 50]


In [8]:
# Exercise 2: 2D indexing
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(arr[1,1])
print(arr[2,0])
print(arr[0])
print(arr[:,2])
print(arr[2,2])


50
70
[10 20 30]
[30 60 90]
90


In [13]:
# Exercise 3: Boolean filtering
numbers = np.array([5, 12, 18, 25, 31, 40, 55])
print(numbers[numbers > 20])
print(numbers[numbers < 20])
print(numbers[(numbers > 15) & (numbers < 40)])

[25 31 40 55]
[ 5 12 18]
[18 25 31]


In [17]:
# Exercise 4: Broadcasting
prices = np.array([
    [100, 200, 300],
    [400, 500, 600]
])
print(prices + 50)
print(prices * 1.10)
print(prices + [10, 20, 30])

[[150 250 350]
 [450 550 650]]
[[110. 220. 330.]
 [440. 550. 660.]]
[[110 220 330]
 [410 520 630]]


In [20]:
# Exercise 5: Aggregation
sales = np.array([
    [100, 200, 300],
    [150, 250, 350],
    [200, 300, 400]
])
print("Total Sales: ", np.sum(sales))
print("Mean Sales: ", np.mean(sales))
print("Maximum Sales: ", np.max(sales))
print("Minimum Sales: ", np.min(sales))
print("Total for each Month: ", np.sum(sales, axis=0) )
print("Total for each store: ", np.sum(sales, axis=1))

Total Sales:  2250
Mean Sales:  250.0
Maximum Sales:  400
Minimum Sales:  100
Total for each Month:  [ 450  750 1050]
Total for each store:  [600 750 900]
