In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)

[10 20 30 40 50]


In [4]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [7]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=np.int32)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int32


In [8]:
arr = np.arange(12)
print(arr.reshape(3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
# vectorization
numbers = np.array([1, 2, 3, 4, 5])
result = numbers * 10
print(result)

[10 20 30 40 50]


In [10]:
predicted = np.array([80, 90, 70, 60])
actual = np.array([85, 88, 75, 65])
errors = predicted - actual
absolute_errors = np.abs(errors)
mae = np.mean(absolute_errors)

print(mae)

4.25


In [ ]:
# Exercise 1:
arr = np.array([[10, 20, 30, 40, 50]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Type: ", arr.dtype)


Shape:  (1, 5)
Dimention:  2
Size:  5
Type:  int64


In [ ]:
# Exercise 2:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape: ", arr.shape)
print("Dimention: ", arr.ndim)
print("Size: ", arr.size)


Shape:  (2, 3)
Dimention:  2
Size:  6


In [ ]:
# Exercise 3:
numbers = np.array([5, 10, 15, 20, 25])
print("Vectorization: ", numbers * 3)


Vectorization:  [15 30 45 60 75]


In [ ]:
# Exercise 4:
prices = np.array([100, 200, 300, 400])
discount = (prices * 20)/100
print("Discount: ", discount)


Discount:  [20. 40. 60. 80.]


In [ ]:
# Exercise 5:
numbers = np.arange(1, 13)
print(numbers.reshape(3, 4))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Exercise 6
predicted = np.array([100, 200, 300, 400])
actual = np.array([110, 190, 320, 380])
error = predicted - actual
absolute_errors = np.abs(error)
mae = np.mean(absolute_errors)
print("Error: ", error)
print("Absolute Error: ", absolute_errors)
print("Mean Absolute Error: ", mae)


Error:  [-10  10 -20  20]
Absolute Error:  [10 10 20 20]
Mean Absolute Error:  15.0
